apiVersion: v1
kind: Service
metadata:
  name: docker-example-sample-service
  namespace: default
  labels:
    app: docker-example-sample-app
spec:
  selector:
    app: docker-example-sample-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP